"use strict";

// tests for createDomain
// Generated by serverless-jest-plugin

const mod = require("../domains/create");

const jestPlugin = require("serverless-jest-plugin");
const lambdaWrapper = jestPlugin.lambdaWrapper;
const wrapped = lambdaWrapper.wrap(mod, { handler: "handler" });

describe("domains.addDomain: Add an entry to match IdP routing rule", () => {
  beforeAll((done) => {
    //  lambdaWrapper.init(liveFunction); // Run the deployed lambda

    done();
  });

  afterEach(() => {
    delete process.env.ABC;
    delete process.env.DEF;
  });

  it("implement tests here", () => {
    process.env.DYNAMODB_TABLE = "okta-domains-dev";
    console.log(process.env.DYNAMODB_TABLE);
    const event = {
      body: {
        domain: "zeesh.org",
        tenant: "zeesh.org",
        idp: "0oaqqgucju9H7WJhc0h7",
        verified: true,
      },
    };
    return wrapped.run(event).then((response) => {
      console.log(JSON.stringify(response));
      expect(response).toBeDefined();
    });
  });
});
