"use strict";

// tests for listDomains
// Generated by serverless-jest-plugin

const mod = require("../domains/list");

const jestPlugin = require("serverless-jest-plugin");
const lambdaWrapper = jestPlugin.lambdaWrapper;
const wrapped = lambdaWrapper.wrap(mod, { handler: "handler" });

describe("listDomains", () => {
  beforeAll((done) => {
    //  lambdaWrapper.init(liveFunction); // Run the deployed lambda

    done();
  });

  it("implement tests here", () => {
    process.env.DYNAMODB_TABLE = "okta-domains-test";
    const event = {
      queryStringParameters: {
        idp: "0oaqqgucju9H7WJhc0h7",
      },
    };
    return wrapped.run(event).then((response) => {
      console.log("Response", JSON.stringify(response));
      expect(response).toBeDefined();
    });
  });
});
