"use strict";

// tests for removeDomain
// Generated by serverless-jest-plugin

const mod = require("../domains/delete");

const jestPlugin = require("serverless-jest-plugin");
const lambdaWrapper = jestPlugin.lambdaWrapper;
const wrapped = lambdaWrapper.wrap(mod, { handler: "handler" });

describe("removeDomain", () => {
  beforeAll((done) => {
    //  lambdaWrapper.init(liveFunction); // Run the deployed lambda

    done();
  });

  it("implement tests here", () => {
    process.env.DYNAMODB_TABLE = "okta-domains-dev";
    const event = {
      pathParameters: {
        name: "zeesh.org",
        idp: "0oaqqgucju9H7WJhc0h7",
      },
    };
    return wrapped.run(event).then((response) => {
      expect(response).toBeDefined();
    });
  });
});
